language: go

go:
  - 1.5

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
  - go get -t ./...
  - curl -sLOf https://raw.githubusercontent.com/rafecolton/fmtpolice/master/coverage
script:
  - go test ./...
  - bash coverage
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci